[build]
  command = yarn build
  publish = ".output/public"

[dev]
  command = "yarn preview"
  targetPort = 3000
  port = 8888
  publish = ".output/public"

[[redirects]]
  from = "/*"
  to = "index.html"
  status = 200
